name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # 만약 브랜치 이름이 master라면 master로 수정하세요.

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # 빌드된 파일이 들어있는 폴더

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
